export const operationsTexts = {
  en: {
    lang: 'en',
    title: 'Operations',
    startDate: 'Start Date',
    endDate: 'End Date',
    userID: 'User ID',
    type: 'Type',
    steps: 'Steps',
    Assets: 'Assets',
    status: 'Status',
    actions: 'Actions',
    sarted: 'Started',
    successful: 'Successful',
    rejected: 'Rejected',
  },
  es: {
    lang: 'es',
    title: 'Operaciones',
    startDate: 'Fecha de inicio',
    endDate: 'Fecha de finalización',
    userID: 'ID de usuario',
    type: 'Tipo',
    steps: 'Pasos',
    Assets: 'Ficheros',
    status: 'Estado',
    actions: 'Acciones',
    sarted: 'Iniciada',
    successful: 'Exitosa',
    rejected: 'Rechazada',
  },
  pt: {
    lang: 'pt',
    title: 'Operações',
    startDate: 'Data de Início',
    endDate: 'Data de Término',
    userID: 'ID do usuário',
    type: 'Tipo',
    steps: 'Passos',
    Assets: /Ativos/,
    status: 'Status',
    actions: /Ações/,
    sarted: 'Iniciado',
    successful: 'Conseguiu',
    rejected: 'Negado',
  }, // TODO: add filters and buttons texts
};
