version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    labels:
      - "dependencies updates"
    reviewers:
      - "MarceloCosta-Facephi"
    assignees:
      - "MarceloCosta-Facephi"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      playwright-deps:
        patterns:
          - "@playwright*"
          - "playwright*"
      test-deps:
        patterns:
          - "jest*"
          - "mocha*"
          - "chai*"
          - "allure*"
      development-deps:
        patterns:
          - "eslint*"
          - "prettier*"
          - "typescript"
    ignore:
      - dependency-name: "typescript"
        versions: ["5.x"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "10:00"
    labels:
      - "github-actions"
    reviewers:
      - "MarceloCosta-Facephi"
    assignees:
      - "MarceloCosta-Facephi"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    auto-merge: true
    groups:
      actions-core:
        patterns:
          - "actions/checkout"
          - "actions/setup-node"
          - "actions/cache"
      actions-pages:
        patterns:
          - "actions/*pages*"