export const dashboardTexts = {
  en: {
    lang: 'en',
    hours: 'hours',
    sevenDays: '7 days',
    thirtyDays: '30 days',
    newOnboardings: 'New onboardings',
    authentications: 'Authentications',
    onboardings: 'Onboardings',
    successRate: 'Success rate',
    errorRate: 'Error rate',
    allOperations: 'All operations (%)',
    succeeded: 'Succeeded',
    started: 'Started',
    expired: 'Expired',
    cancelled: 'Cancelled',
    blocked: 'Blocked',
    denied: 'Denied',
    error: 'Error',
  },
  es: {
    lang: 'es',
    hours: 'horas',
    sevenDays: '7 días',
    thirtyDays: '30 días',
    newOnboardings: 'Nuevos registros',
    authentications: 'Autenticaciones',
    onboardings: 'Onboardings',
    successRate: 'Tasa de éxito',
    errorRate: 'Tasa de errores',
    allOperations: 'Todas las operaciones (%)',
    succeeded: 'Exitoso',
    started: 'Iniciado',
    expired: 'Expirado',
    cancelled: 'Cancelado',
    blocked: 'Bloqueado',
    denied: 'Denegado',
    error: 'Error',
  },
  pt: {
    lang: 'pt',
    hours: 'horas',
    sevenDays: '7 dias',
    thirtyDays: '30 dias',
    newOnboardings: 'Novos registros',
    authentications: 'Autenticações',
    onboardings: 'Onboardings',
    successRate: 'Taxa de sucesso',
    errorRate: 'Taxa de erro',
    allOperations: 'Todas as operações (%)',
    succeeded: 'Bem-sucedido',
    started: 'Iniciado',
    expired: 'Expirado',
    cancelled: 'Cancelado',
    blocked: 'Bloqueado',
    denied: 'Negado',
    error: 'Erro',
  },
};
