name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.51.0-noble
      options: --ipc=host
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3]
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Enable Corepack
        run: corepack enable
        shell: bash
      
      - name: Install Correct Yarn Version
        run: yarn set version 4.7.0
        shell: bash

      - name: Install dependencies
        run: yarn install --immutable
        shell: bash

      - name: Create auth directory
        run: mkdir -p auth
        shell: bash

      - name: Run Playwright tests separated by browser
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          USER_EMAIL_1: ${{ secrets.USER_EMAIL_1 }}
          USER_PASSWORD_1: ${{ secrets.USER_PASSWORD_1 }}
          BASE_URL: ${{ vars.BASE_URL || 'https://idv-suite.identity-platform.dev' }}
          HOME: /root
        run: yarn playwright test --shard=${{ matrix.shardIndex }}/3
        continue-on-error: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: allure-results-${{ matrix.shardIndex }}
          path: allure-results
          retention-days: 30

  publish-report:
    if: always()
    needs: [playwright-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Generate and Publish Allure Report
        uses: Valiantsin2021/allure-shard-results-publish@1.0.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-pattern: 'allure-results-*'
          results-directory: 'combined-allure-results'
          report-directory: 'allure-report'
          history-directory: 'allure-history'
          gh-pages: 'gh-pages'
          gh-pages-branch: 'gh-pages'
          retention-days: '30'
          publish-to-pages: 'true'
          fail-on-empty-results: 'false'
          add-env: 'true'