name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.50.1-noble
      options: --ipc=host
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3]
        shardTotal: [3]
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Enable Corepack
        run: corepack enable
        shell: bash

      - uses: actions/setup-node@v4.2.0
        with:
          node-version: "20.17.0"
          cache: "yarn"
      
      - name: Install Correct Yarn Version
        run: yarn set version 4.6.0
        shell: bash

      - name: Install dependencies
        run: yarn install --immutable
        shell: bash

      - name: Create auth directory
        run: mkdir -p auth
        shell: bash

      - name: Run Playwright tests separated by browser
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          USER_EMAIL_1: ${{ secrets.USER_EMAIL_1 }}
          USER_PASSWORD_1: ${{ secrets.USER_PASSWORD_1 }}
          BASE_URL: ${{ vars.BASE_URL || 'https://idv-suite.identity-platform.dev' }}
        run: yarn playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        continue-on-error: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: allure-results-${{ matrix.shardIndex }}
          path: allure-results
          retention-days: 30

  merge-reports:
    if: always()
    needs: [playwright-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable
        shell: bash

      - uses: actions/setup-node@v4.2.0
        with:
          node-version: "20.17.0"
          cache: "yarn"
      
      - name: Install Correct Yarn Version
        run: yarn set version 4.6.0
        shell: bash

      - name: Install dependencies
        run: yarn install --immutable
        shell: bash

      - name: Download all test results
        uses: actions/download-artifact@v4
        with:
          pattern: allure-results-*
          path: allure-results
          merge-multiple: true

      - name: Generate Allure Report
        run: |
          yarn dlx allure-commandline generate allure-results --clean -o allure-report
        shell: bash

      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v5

      - name: Upload Allure Report to GitHub Pages
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "allure-report"

  deploy:
    if: always()
    needs: merge-reports
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5