name: E2E Testing
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install -g npm@latest
          npm ci --prefer-offline

      - name: Install Playwright Dependencies
        run: npm install --save-dev @playwright/test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Download and cache Playwright browsers
        id: cache-browsers
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright/chromium-*
            ~/.cache/ms-playwright/firefox-*
            ~/.cache/ms-playwright/webkit-*
          key: ${{ runner.os }}-playwright-browsers-${{ hashFiles('package-lock.json') }}

      - name: Run tests
        continue-on-error: true
        env:
            USER_EMAIL: ${{ secrets.USER_EMAIL }}
            USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: npx playwright test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: playwright-results
          path: |
            test-results
          retention-days: 30

      - name: Generate Allure Report
        if: always()
        run: |
          npm install -g allure-commandline
          allure generate allure-results --clean -o allure-report

      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v5.0.0
        with:
          enablement: true

      - name: Upload artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'allure-report'

  deploy:
    if: always()
    needs: test-e2e
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4